import type { Metadata } from "next";
import { Anton, Inter } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import { Analytics } from "@vercel/analytics/next";
import Script from "next/script";
import "./globals.css";
import { site } from "@/app/lib/site";
import { ConsentBanner } from "@/app/components/consent-banner";
import { AnalyticsClickBridge } from "@/app/components/analytics-click-bridge";
import { LanguageHintBanner } from "@/app/components/language-hint-banner";
import { WhatsAppFab } from "@/app/components/whatsapp-fab";
import { hreflangAlternates } from "@/app/lib/i18n";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const isProd = process.env.VERCEL_ENV === "production";

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `${site.name} — ${site.tagline}`,
    template: `%s — ${site.name}`,
  },
  description: site.description,
  applicationName: site.name,
  keywords: [
    "quad tours Cascais",
    "quad bike Guincho",
    "buggy Guincho",
    "sea kayak Cascais",
    "mountain bike Sintra",
    "hiking Sintra",
    "Sintra Jeep tour",
    "stag party Cascais",
    "corporate event Cascais",
    "Guincho Adventours",
  ],
  authors: [{ name: site.legalName }],
  category: "travel",
  alternates: {
    canonical: site.url,
    languages: hreflangAlternates("/"),
  },
  openGraph: {
    type: "website",
    url: site.url,
    siteName: site.name,
    locale: "en_GB",
    title: `${site.name} — ${site.tagline}`,
    description: site.description,
    // OG image is auto-generated by app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: `${site.name} — ${site.tagline}`,
    description: site.description,
    // Twitter image is auto-generated by app/twitter-image.tsx.
  },
  robots: isProd
    ? { index: true, follow: true }
    : { index: false, follow: false, nocache: true },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const gaId = process.env.NEXT_PUBLIC_GA_ID;

  return (
    <html lang="en" className={`${inter.variable} ${anton.variable}`}>
      <body>
        {/* Consent Mode v2 — default all storage to denied.
            The consent banner flips this to granted on Accept. */}
        {gaId && (
          <Script id="consent-default" strategy="beforeInteractive">
            {`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}
              gtag('consent','default',{
                ad_storage:'denied',
                analytics_storage:'denied',
                functionality_storage:'denied',
                personalization_storage:'denied',
                security_storage:'granted',
                wait_for_update:500
              });`}
          </Script>
        )}

        {children}

        {/* Cookieless first-party counting — runs regardless of the consent
            banner (no cookies, no PII) and captures the visitors GA4 misses
            when consent is declined. */}
        <Analytics />
        {gaId && <GoogleAnalytics gaId={gaId} />}
        {gaId && <AnalyticsClickBridge />}
        <ConsentBanner enabled={Boolean(gaId)} />
        <LanguageHintBanner />
        <WhatsAppFab />
      </body>
    </html>
  );
}
